services:
  - type: web
    name: mealprint
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn manual_app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
